export const FETCH_NEW_PRODUCTS = 'FETCH_NEW_PRODUCTS';
export const FETCH_NEW_PRODUCT_SUCCESS = 'FETCH_NEW_PRODUCT_SUCCESS';
export const FETCH_NEW_PRODUCT_FAILED = 'FETCH_NEW_PRODUCT_FAILED';

export const FETCH_HOT_SALES = 'FETCH_HOT_SALES';
export const FETCH_HOT_SALES_SUCCESS = 'FETCH_HOT_SALES_SUCCESS';
export const FETCH_HOT_SALES_FAILED = 'FETCH_HOT_SALES_FAILED';

export const FETCH_BLOG_CONTENT = 'FETCH_BLOG_CONTENT';
export const FETCH_BLOG_CONTENT_SUCCESS = 'FETCH_BLOG_CONTENT_SUCCESS';
export const FETCH_BLOG_CONTENT_FALIED = 'FETCH_BLOG_CONTENT_FALIED';

export const FETCH_BLOG_CUSTOMER = 'FETCH_BLOG_CUSTOMER';
export const FETCH_BLOG_CUSTOMER_SUCCESS = 'FETCH_BLOG_CUSTOMER_SUCCESS';
export const FETCH_BLOG_CUSTOMER_FALIED = 'FETCH_BLOG_CUSTOMER_FALIED';

export const FETCH_BREADCRUMB_PRODUCT = 'FETCH_BREADCRUMB_PRODUCT_PAGE';
export const FETCH_BREADCRUMB_PRODUCT_SUCCESS = 'FETCH_BREADCRUMB_PRODUCT_PAGE_SUCCESS';
export const FETCH_BREADCRUMB_PRODUCT_FAILED = 'FETCH_BREADCRUMB_PRODUCT_PAGE_FAILED';

export const FETCH_LIST_PRODUCT_GRID = 'FETCH_BREADCRUMB_LIST_GRID';
export const FETCH_LIST_PRODUCT_GRID_SUCCESS = 'FETCH_LIST_PRODUCT_GRID_SUCCESS';
export const FETCH_LIST_PRODUCT_GRID_FAILED = 'FETCH_LIST_PRODUCT_GRID_FAILED';

export const FETCH_LIST_PRODUCT = 'FETCH_LIST_PRODUCT';
export const FETCH_LIST_PRODUCT_SUCCESS = 'FETCH_LIST_PRODUCT_SUCCESS';
export const FETCH_LIST_PRODUCT_FAILED = 'FETCH_LIST_PRODUCT_FAILED';

export const FETCH_PRODUCT_TAG = 'FETCH_PRODUCT_TAG';
export const FETCH_PRODUCT_TAG_SUCCESS = 'FETCH_PRODUCT_TAG_SUCCESS';
export const FETCH_PRODUCT_TAG_FAILED = 'FETCH_PRODUCT_TAG_FAILED';

export const FETCH_PRODUCT_CATEGORY = 'FETCH_PRODUCT_CATEGORY';
export const FETCH_PRODUCT_CATEGORY_SUCCESS = 'FETCH_PRODUCT_CATEGORY_SUCCESS';
export const FETCH_PRODUCT_CATEGORY_FAILED = 'FETCH_PRODUCT_CATEGORY_FAILED';

export const FETCH_BLOG_PAGE = 'FETCH_BLOG_PAGE';
export const FETCH_BLOG_PAGE_SUCCESS = 'FETCH_BLOG_PAGE_SUCCESS';
export const FETCH_BLOG_PAGE_FAILED = 'FETCH_BLOG_PAGE_FAILED';

export const FETCH_BLOG_WITH_ID = 'FETCH_BLOG_WITH_ID';
export const FETCH_BLOG_PAGE_WITH_ID_SUCCESS = 'FETCH_BLOG_PAGE_WITH_ID_SUCCESS';
export const FETCH_BLOG_PAGE_WITH_ID_FAILED = 'FETCH_BLOG_PAGE_WITH_ID_FAILED';
